version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=battery
    depends_on:
      - db
    command: >
      sh -c "sleep 5 && flask db upgrade && python app.py"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=battery
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: