"""required fields

Revision ID: 46549518c109
Revises: ace3ae7d7284
Create Date: 2025-10-13 15:37:58.271916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46549518c109'
down_revision = 'ace3ae7d7284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.alter_column('voltage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('voltage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###
