"""history in battery

Revision ID: 7e6d8db8120a
Revises: 46549518c109
Create Date: 2025-10-13 16:10:30.211918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6d8db8120a'
down_revision = '46549518c109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity_history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.drop_column('capacity_history')

    # ### end Alembic commands ###
